services:
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data

  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main

volumes:
#  redis-data:
#    driver: local
  postgres:
    driver: local
